package com.lineage.server;

import com.lineage.config.Config;
import com.lineage.config.ConfigAlt;
import com.lineage.config.ConfigOther;
import com.lineage.config.ConfigRate;
import com.lineage.config.ConfigSQL;
import com.lineage.echo.PacketHandler;
import com.lineage.list.BadNamesList;
import com.lineage.server.datatables.ArmorSetTable;
import com.lineage.server.datatables.BeginnerTable;
import com.lineage.server.datatables.CastleWarGiftTable;
import com.lineage.server.datatables.CharObjidTable;
import com.lineage.server.datatables.CommandsTable;
import com.lineage.server.datatables.DollPowerTable;
import com.lineage.server.datatables.DoorSpawnTable;
import com.lineage.server.datatables.DropItemTable;
import com.lineage.server.datatables.DropLimitTable;
import com.lineage.server.datatables.DropMapTable;
import com.lineage.server.datatables.DropMobTable;
import com.lineage.server.datatables.DropTable;
import com.lineage.server.datatables.DungeonRTable;
import com.lineage.server.datatables.DungeonTable;
import com.lineage.server.datatables.EventSpawnTable;
import com.lineage.server.datatables.EventTable;
import com.lineage.server.datatables.ExpTable;
import com.lineage.server.datatables.FishingTable;
import com.lineage.server.datatables.GetBackRestartTable;
import com.lineage.server.datatables.GetbackTable;
import com.lineage.server.datatables.GfxIdOrginal;
import com.lineage.server.datatables.InnTable;
import com.lineage.server.datatables.ItemBoxTable;
import com.lineage.server.datatables.ItemBsgTable;
import com.lineage.server.datatables.ItemMsgTable;
import com.lineage.server.datatables.ItemPowerUpdateTable;
import com.lineage.server.datatables.ItemRestrictionsTable;
import com.lineage.server.datatables.ItemTable;
import com.lineage.server.datatables.ItemTeleportTable;
import com.lineage.server.datatables.ItemTimeTable;
import com.lineage.server.datatables.Item_Box_Table;
import com.lineage.server.datatables.Item_Dolls_Table;
import com.lineage.server.datatables.Item_Make_Table;
import com.lineage.server.datatables.Item_Poly_Table;
import com.lineage.server.datatables.Item_Teleport_Table;
import com.lineage.server.datatables.LoadZnoe;
import com.lineage.server.datatables.MapExpTable;
import com.lineage.server.datatables.MapLevelTable;
import com.lineage.server.datatables.MapsTable;
import com.lineage.server.datatables.MobGroupTable;
import com.lineage.server.datatables.NPCTalkDataTable;
import com.lineage.server.datatables.NpcActionTable;
import com.lineage.server.datatables.NpcChatTable;
import com.lineage.server.datatables.NpcScoreTable;
import com.lineage.server.datatables.NpcSpawnTable;
import com.lineage.server.datatables.NpcTable;
import com.lineage.server.datatables.NpcTeleportTable;
import com.lineage.server.datatables.PetItemTable;
import com.lineage.server.datatables.PetTypeTable;
import com.lineage.server.datatables.PolyTable;
import com.lineage.server.datatables.QuestMapTable;
import com.lineage.server.datatables.ResolventTable;
import com.lineage.server.datatables.SceneryTable;
import com.lineage.server.datatables.ShopCnTable;
import com.lineage.server.datatables.ShopTable;
import com.lineage.server.datatables.SkillsItemTable;
import com.lineage.server.datatables.SkillsTable;
import com.lineage.server.datatables.SpawnTable;
import com.lineage.server.datatables.SprTable;
import com.lineage.server.datatables.TownSetTable;
import com.lineage.server.datatables.TrapTable;
import com.lineage.server.datatables.TrapsSpawn;
import com.lineage.server.datatables.WeaponPowerTable;
import com.lineage.server.datatables.WeaponSkillTable;
import com.lineage.server.datatables.lock.AccountReading;
import com.lineage.server.datatables.lock.AuctionBoardReading;
import com.lineage.server.datatables.lock.BoardReading;
import com.lineage.server.datatables.lock.BuddyReading;
import com.lineage.server.datatables.lock.CastleReading;
import com.lineage.server.datatables.lock.CharBookConfigReading;
import com.lineage.server.datatables.lock.CharBookReading;
import com.lineage.server.datatables.lock.CharBuffReading;
import com.lineage.server.datatables.lock.CharItemsReading;
import com.lineage.server.datatables.lock.CharItemsTimeReading;
import com.lineage.server.datatables.lock.CharOtherReading;
import com.lineage.server.datatables.lock.CharSkillReading;
import com.lineage.server.datatables.lock.CharacterConfigReading;
import com.lineage.server.datatables.lock.CharacterQuestReading;
import com.lineage.server.datatables.lock.ClanEmblemReading;
import com.lineage.server.datatables.lock.ClanReading;
import com.lineage.server.datatables.lock.DwarfForClanReading;
import com.lineage.server.datatables.lock.DwarfForElfReading;
import com.lineage.server.datatables.lock.DwarfReading;
import com.lineage.server.datatables.lock.FurnitureSpawnReading;
import com.lineage.server.datatables.lock.HouseReading;
import com.lineage.server.datatables.lock.IpReading;
import com.lineage.server.datatables.lock.MailReading;
import com.lineage.server.datatables.lock.PetReading;
import com.lineage.server.datatables.lock.ServerReading;
import com.lineage.server.datatables.lock.SpawnBossReading;
import com.lineage.server.datatables.lock.TownReading;
import com.lineage.server.datatables.sql.CharacterTable;
import com.lineage.server.model.Instance.L1DoorInstance;
import com.lineage.server.model.Instance.L1ItemPower;
import com.lineage.server.model.Instance.L1PcInstance;
import com.lineage.server.model.L1AttackList;
import com.lineage.server.model.L1CastleLocation;
import com.lineage.server.model.L1ClanMatching;
import com.lineage.server.model.L1DeleteItemOnGround;
import com.lineage.server.model.gametime.L1GameTimeClock;
import com.lineage.server.model.map.L1WorldMap;
import com.lineage.server.model.skill.L1SkillId;
import com.lineage.server.model.skill.L1SkillMode;
import com.lineage.server.templates.L1PcOther;
import com.lineage.server.thread.GeneralThreadPool;
import com.lineage.server.thread.NpcAiThreadPool;
import com.lineage.server.thread.PcOtherThreadPool;
import com.lineage.server.timecontroller.StartTimer_Event;
import com.lineage.server.timecontroller.StartTimer_Npc;
import com.lineage.server.timecontroller.StartTimer_Pc;
import com.lineage.server.timecontroller.StartTimer_Pet;
import com.lineage.server.timecontroller.StartTimer_Server;
import com.lineage.server.timecontroller.StartTimer_Skill;
import com.lineage.server.timecontroller.server.ServerResetDailyItemTimer;
import com.lineage.server.utils.PerformanceTimer;
import com.lineage.server.world.World;
import com.lineage.server.world.WorldCrown;
import com.lineage.server.world.WorldDarkelf;
import com.lineage.server.world.WorldDragonKnight;
import com.lineage.server.world.WorldElf;
import com.lineage.server.world.WorldIllusionist;
import com.lineage.server.world.WorldKnight;
import com.lineage.server.world.WorldPet;
import com.lineage.server.world.WorldSummons;
import com.lineage.server.world.WorldWizard;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import william.L1SystemMessageTable;
import william.Plug_Question;

public class GameServer {
    private static GameServer _instance;
    private static final Log _log = LogFactory.getLog(GameServer.class);

    public static GameServer getInstance() {
        if (_instance == null) {
            _instance = new GameServer();
        }
        return _instance;
    }

    public void initialize() {
        PerformanceTimer timer = new PerformanceTimer();
        try {
            _log.info("\n\r--------------------------------------------------\n\r       外部設置：經驗倍率: " + ConfigRate.RATE_XP + "\n\r       外部設置：正義質倍率: " + ConfigRate.RATE_LA + "\n\r       外部設置：有好度倍率: " + ConfigRate.RATE_KARMA + "\n\r       外部設置：物品掉落倍率: " + ConfigRate.RATE_DROP_ITEMS + "\n\r       外部設置：金幣掉落倍率: " + ConfigRate.RATE_DROP_ADENA + "\n\r       外部設置：廣播等級限制: " + ((int) ConfigAlt.GLOBAL_CHAT_LEVEL) + "\n\r       外部設置：PK設置: " + (ConfigAlt.ALT_NONPVP ? "允許" : "不允許") + "\n\r       外部設置：最大連線設置: " + ((int) Config.MAX_ONLINE_USERS) + "\n\r--------------------------------------------------");
            PacketHandler.load();
            ServerReading.get().load();
            IdFactory.get().load();
            CharObjidTable.get().load();
            AccountReading.get().load();
            GeneralThreadPool.get();
            PcOtherThreadPool.get();
            NpcAiThreadPool.get();
            ExpTable.get().load();
            SprTable.get().load();
            MapsTable.get().load();
            MapExpTable.get().load();
            MapLevelTable.get().load();
            ItemTimeTable.get().load();
            L1WorldMap.get().load();
            L1GameTimeClock.init();
            NpcTable.get().load();
            NpcScoreTable.get().load();
            CharacterTable.loadAllCharName();
            CharacterTable.clearOnlineStatus();
            World.get();
            WorldCrown.get();
            WorldKnight.get();
            WorldElf.get();
            WorldWizard.get();
            WorldDarkelf.get();
            WorldDragonKnight.get();
            WorldIllusionist.get();
            WorldPet.get();
            WorldSummons.get();
            TrapTable.get().load();
            TrapsSpawn.get().load();
            ItemTable.get().load();
            DropTable.get().load();
            DropMapTable.get().load();
            DropMobTable.get();
            DropLimitTable.get();
            DropItemTable.get().load();
            SkillsTable.get().load();
            SkillsItemTable.get().load();
            MobGroupTable.get().load();
            SpawnTable.get().load();
            PolyTable.get().load();
            ShopTable.get().load();
            ShopCnTable.get().load();
            DungeonTable.get().load();
            DungeonRTable.get().load();
            NPCTalkDataTable.get().load();
            NpcSpawnTable.get().load();
            DwarfForClanReading.get().load();
            ClanReading.get().load();
            ClanEmblemReading.get().load();
            L1ClanMatching.getInstance().loadClanMatching();
            CastleReading.get().load();
            L1CastleLocation.setCastleTaxRate();
            GetBackRestartTable.get().load();
            DoorSpawnTable.get().load();
            WeaponSkillTable.get().load();
            NpcActionTable.load();
            GetbackTable.loadGetBack();
            PetTypeTable.load();
            PetItemTable.get().load();
            Item_Poly_Table.get().load();
            Item_Dolls_Table.get().load();
            ItemMsgTable.get().load();
            ItemBsgTable.get().load();
            Item_Make_Table.get().load();
            ItemBoxTable.get().load();
            Item_Box_Table.get().load();
            ResolventTable.get().load();
            new L1DeleteItemOnGround().initialize();
            NpcTeleportTable.get().load();
            NpcChatTable.get().load();
            ArmorSetTable.get().load();
            ItemTeleportTable.get().load();
            Item_Teleport_Table.get().load();
            ItemPowerUpdateTable.get().load();
            CommandsTable.get().load();
            BeginnerTable.get().load();
            L1SystemMessageTable.get().loadSystemMessage();
            ServerResetDailyItemTimer.ResetDailyItem();
            ItemRestrictionsTable.get().load();
            SpawnBossReading.get().load();
            HouseReading.get().load();
            IpReading.get().load();
            TownReading.get().load();
            TownSetTable.get().load();
            MailReading.get().load();
            AuctionBoardReading.get().load();
            BoardReading.get().load();
            CharBuffReading.get().load();
            CharSkillReading.get().load();
            CharacterConfigReading.get().load();
            BuddyReading.get().load();
            CharBookReading.get().load();
            CharBookConfigReading.get().load();
            CharOtherReading.get().load();
            CharacterQuestReading.get().load();
            BadNamesList.get().load();
            SceneryTable.get().load();
            L1SkillMode.get().load();
            L1AttackList.load();
            L1ItemPower.load();
            L1PcInstance.load();
            CharItemsReading.get().load();
            DwarfReading.get().load();
            DwarfForElfReading.get().load();
            DollPowerTable.get().load();
            PetReading.get().load();
            CharItemsTimeReading.get().load();
            L1PcOther.load();
            EventTable.get().load();
            Thread.sleep((long) ConfigOther.Gamesleep * L1SkillId.STATUS_BRAVE);
            if (EventTable.get().size() > 0) {
                EventSpawnTable.get().load();
            }
            Plug_Question.getInstance();
            QuestMapTable.get().load();
            FurnitureSpawnReading.get().load();
            GfxIdOrginal.get();
            LoadZnoe.getInstance().load();
            WeaponPowerTable.get().load();
            FishingTable.get().load();
            CastleWarGiftTable.get().load();
            InnTable.getInstance();
            new StartTimer_Server().start();
            new StartTimer_Pc().start();
            new StartTimer_Npc().start();
            new StartTimer_Pet().start();
            new StartTimer_Skill().start();
            new StartTimer_Event().start();
            Runtime.getRuntime().addShutdownHook(Shutdown.getInstance());
            EchoServerTimer.get().start();
            L1DoorInstance.openDoor();
        } catch (Exception e) {
            _log.error(e.getLocalizedMessage(), e);
        } catch (Throwable throwable) {
            throwable.printStackTrace();
        } finally {
            _log.info("\n\r--------------------------------------------------\n\r       遊戲伺服器核心版本: 3.63C Lineage3.63C\n\r\n\r       Server Verion: 120913203\n\r       Cache Verion: 120913200\n\r       Auth Verion: 2010083002\n\r       Npc Verion: 120913201\n\r\n\r       主機位置: " + Config.GAME_SERVER_HOST_NAME + "\n\r       監聽端口: " + Config.GAME_SERVER_PORT + "\n\r\n\r       伺服器作業系統: " + System.getProperties().getProperty("os.name") + "\n\r       伺服器使用者: " + System.getProperties().getProperty("user.name") + "\n\r       使用者名稱資料庫: " + ConfigSQL.DB_URL2_LOGIN + "\n\r       伺服器檔案資料庫: " + ConfigSQL.DB_URL2 + "\n\r       綁定登入器設置: " + Config.LOGINS_TO_AUTOENTICATION + "\n\r--------------------------------------------------");
            new CmdEcho(timer.get()).runCmd();
        }
    }
}
